apiVersion: v1
kind: Service
metadata:
  name: notepad-service-staging
  labels:
    app: notepad
    env: staging
spec:
  selector:
    app: notepad
    env: staging
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31110
  type: NodePort
