apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notepad-deployment-staging
  labels:
    app: notepad
    env: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notepad
        env: staging
    spec:
      containers:
      - name: notepad-staging
        image: NOTEPAD_CONTAINER_IMAGE
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: notepad-logback-volume
          mountPath: /etc/notepad
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: staging
          - name: staging_datasource_url
            value: jdbc:mysql://mysql-service-staging:3306/notepad
          - name: staging_datasource_username
            value: root
          - name: staging_datasource_password
            valueFrom:
              secretKeyRef:
                name: mysql-staging-root-password-secret
                key: PASSWORD
          - name: JVM_ARGS
            value: "-Xmx256m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
      - name: notepad-logback-volume
        configMap:
          name: notepad-logback-staging-configmap
