apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-production
  labels:
    app: mysql
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      env: production  
  template:
    metadata:
      labels:
        app: mysql
        env: production
    spec:
      containers:
      - name: mysql-production
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: notepad
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-production-root-password-secret
                key: PASSWORD
