apiVersion: v1
kind: Service
metadata:
  name: notepad-service-production
  labels:
    app: notepad
    env: production
spec:
  selector:
    app: notepad
    env: production
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31120
  type: NodePort
